### PR TITLE
(WIP) Fix for flutter 1.6 above.

### PR DESCRIPTION
**Pull request by awazgyawali**
Changed the api calls, this PR is work in progress as it depends upon stream_channel where I have sent another PR to address this issue.

### CODE REVIEW

**Comment by awazgyawali** [comment]
Hi @lukaspili, it seems that you have abandoned this project. Are you ok to give someone full access to the repo so that they can maintain it? If you are comfortable with it then I would like to work on it as my organization heavily relies on this plugin and I want to add more to it.

**Comment by lukaspili** [comment]
Hello @awazgyawali @nabinkh, I apologize for the very late response. My organization plans to restart maintenance of this plugin, starting in January. 
Are you still interested to join? I can give you a write access right now, so you can merge your work.

**Comment by awazgyawali** [comment]
Hi @lukaspili happy to see you back. We initially tried to maintain this project but as you were not available ATM we tweaked the project in such a way that now it only scans our beacons. So this PR shall not be merged else it will bring very false result.

@nabinkh and I are from the same team and we are also planning to build a package from scratch from around January. We shall continue working at that time, but for now, I am afraid I have to close this PR for the sake of sanity.

**Comment by lukaspili** [comment]
Sure. Sorry again for replying so late!

**Pull request closed without merging**
